name: Create and push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create test folder and file.
      run: mkdir -p data/
      run: touch data/$(date +"%Y-%m-%d-%H:%M:%S")

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'data/'
        destination_repo: 'ofey404/push-file-test'
        destination_folder: ''
        user_email: 'ofey404@gmail.com'
        user_name: 'Ofey Chan'
        commit_message: 'Test for create folder and file.'
